# Generated by Django 5.2 on 2025-04-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200, verbose_name='Nom et Prénom')),
                ('departement', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('PROF', 'Professeur'), ('MCF', 'Maître de Conférences'), ('MC', 'Maître Assistant'), ('ASS', 'Assistant'), ('AUTRE', 'Autre grade')], max_length=20)),
                ('cours', models.CharField(max_length=200)),
                ('heures_td', models.IntegerField(default=0, verbose_name='Heures TD')),
                ('heures_tp', models.IntegerField(default=0, verbose_name='Heures TP')),
                ('coefficient', models.FloatField(default=1.0)),
                ('seances_surveillance', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['nom_prenom'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indisponibilites', models.JSONField(default=list, help_text="Liste des indisponibilités sous forme [{'date': 'YYYY-MM-DD', 'seance': 's1'}, ...]")),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='playground.enseignant')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['enseignant'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=10)),
                ('matiere', models.CharField(max_length=50)),
                ('profResponsable', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('seance', models.CharField(choices=[('s1', '08:30-10:00'), ('s2', '10:45-12:15'), ('s3', '13:00-14:30'), ('s4', '15:15-16:45')], default='s1', max_length=2)),
                ('nb_salle', models.PositiveIntegerField(default=1)),
                ('professor_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_as_prof_1', to='playground.enseignant')),
                ('professor_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_as_prof_2', to='playground.enseignant')),
            ],
        ),
    ]
