# Generated by Django 5.2 on 2025-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_remove_session_professor_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='nb_prof_aff',
            field=models.IntegerField(default=1.0),
        ),
    ]
