# Generated by Django 5.2 on 2025-04-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_session_nb_prof_aff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='session',
            name='profResponsable',
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=50)),
                ('profResponsable', models.CharField(max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='playground.session')),
            ],
        ),
    ]
