# Generated by Django 5.2 on 2025-04-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_remove_session_matiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='role',
            field=models.CharField(choices=[('S', 'Surveillant'), ('RS', 'Responsable + Surveillant'), ('R', 'Responsable Seulement')], max_length=4, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(max_length=20),
        ),
    ]
