# Generated by Django 5.2 on 2025-04-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_affectation_role_alter_session_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='role',
            field=models.CharField(max_length=4),
        ),
    ]
