# Generated by Django 5.2 on 2025-04-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_alter_affectation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='profResponsable',
            field=models.CharField(max_length=200, verbose_name='Nom et Prénom'),
        ),
    ]
