# Generated by Django 5.2 on 2025-04-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_alter_devoir_profresponsable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enseignant',
            constraint=models.UniqueConstraint(fields=('nom_prenom', 'departement', 'grade'), name='unique_enseignant'),
        ),
    ]
